[versions]
agp = "8.12.3"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
constraintlayout = "2.2.1"
navigationFragmentKtx = "2.9.6"
navigationUiKtx = "2.9.6"
map = "19.2.0"
gpuimage = "2.1.0"
glide = "5.0.5"
ucrop = "2.2.10"
biometric = "1.1.0"
securityCrypto = "1.1.0"
okhttp = "5.3.0"
youtubeplayer = "13.0.0"
swiperefreshlayout = "1.1.0"
aboutlibraries = "12.2.4"
mpandroidchart = "3.1.0"

shipbook = "1.8.3"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
map = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "map" }
gpuimage = {group = "jp.co.cyberagent.android", name = "gpuimage", version.ref = "gpuimage"}
glide = {group = "com.github.bumptech.glide", name = "glide", version.ref = "glide"}
ucrop = { group = "com.github.yalantis", name = "ucrop", version.ref = "ucrop" }
biometric = {group = "androidx.biometric", name = "biometric", version.ref = "biometric"}
securityCrypto = {group = "androidx.security", name = "security-crypto", version.ref = "securityCrypto"}
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
youtube-player = { group = "com.pierfrancescosoffritti.androidyoutubeplayer", name = "core", version.ref = "youtubeplayer" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }
aboutlibraries = { group = "com.mikepenz", name = "aboutlibraries", version.ref = "aboutlibraries" }
mpandroidchart = { group = "com.github.PhilJay", name = "MPAndroidChart", version.ref = "mpandroidchart" }

shipbook = { group = "io.shipbook", name = "shipbooksdk", version.ref = "shipbook" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

